#! /usr/bin/env bash
set -e

get_input() {
  var_name=${1}
  if [[ -z "${!var_name}" ]]; then
    message=${2}
    extra_args=${3:-""}
    read ${extra_args} -p "${message}" ${var_name}
    echo "export ${var_name}='${!var_name}'" >> .demo_settings
  else
    echo "${var_name} already set, skipping."
  fi
}

get_hidden_input() {
  var_name=${1}
  message=${2}
  if [[ -z "${!var_name}" ]]; then
      get_input "${var_name}" "${message}" -s
      echo ""
  fi
}

if [[ -f .demo_settings ]]; then
    echo "Loading previous settings from .demo_settings"
    . .demo_settings
fi

echo "This will create several secrets and inputs files to enable running the examples."
echo "It is not recommended that you continue if you are using a shared manager."
get_input private_key_path "Enter path to SSH key with access to servers on openstack: "
echo ""

get_input key_name "Enter key name for key on openstack corresponding to private key path: "
get_input keystone_url "Enter keystone URL (e.g. https://openstack-api.example:5000/v3): "
get_input keystone_username "Enter keystone username: "
get_hidden_input keystone_password "Enter keystone password: "
get_input keystone_tenant_name "Enter keystone tenant name: "
get_input region "Enter keystone region: "
get_input centos7_image_id "Enter Centos 7 image UUID: "
get_input flavor_id "Enter small or medium flavor UUID: "
get_input manager_network "Enter openstack network name for network with cloudify manager: "
get_input floating_ip_network_id "Enter UUID of network for floating IPs: "
echo ""

get_input cloudify_username "Enter cloudify manager username: "
get_hidden_input cloudify_password "Enter cloudify manager password: "
echo ""

echo "Removing existing secrets (where applicable)..."
for secret in agent_key_private keystone_url keystone_username keystone_password keystone_tenant_name region; do
  cfy secrets delete ${secret} >/dev/null 2>/dev/null
done

echo "Creating secrets"
cfy secrets create -f ${private_key_path} agent_key_private
cfy secrets create -s ${keystone_url} keystone_url
cfy secrets create -s ${keystone_username} keystone_username
cfy secrets create -s ${keystone_password} keystone_password
cfy secrets create -s ${keystone_tenant_name} keystone_tenant_name
cfy secrets create -s ${region} region
cfy secrets create -s ${cloudify_username} cloudify_manager_username
cfy secrets create -s ${cloudify_password} cloudify_manager_password

echo "Creating nagios install inputs"
echo "floating_network_id: ${floating_ip_network_id}
image: ${centos7_image_id}
flavor: ${flavor_id}
management_network_name: ${manager_network}
key_name: ${key_name}" > nagios-blueprint-inputs.yaml

echo "Creating snmp test server install inputs"
echo "image: ${centos7_image_id}
flavor: ${flavor_id}
management_network_name: ${manager_network}
key_name: ${key_name}" > snmptest-blueprint-inputs.yaml
